service: teknowlogy-database-layer

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
  region: eu-west-3

layers:
  teknowlogy-database-layer:
    path: nodejs
    description: 'PostGres transactions layer for teknowlogy group'
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs12.x
      - nodejs10.x
    package:
      exclude:
        - nodejs/node_modules/aws-sdk/**